### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by mrzaxaryan** [jagenjo/Canvas2DtoWebGL#10]
Hi what an awesome project!
Maybe you can add resizing support?
I added `gl.viewport(0, 0, gl.canvas.width, gl.canvas.height);`  into **start2d** function.
Is it good idea?

**Comment by jagenjo** [comment]
Hi, thanks!

I cant add changing the gl.viewport because sometimes you want to draw just to a tiny part of the viewport, but feel free to call gl.viewport before calling start2D.
