### ISSUE TITLE
Implementing shadowblur

### ISSUE THREAD

**Issue by AlexVestin** [jagenjo/Canvas2DtoWebGL#11]
Hi, awesome project!
are there plans to implement the shadowblur from the canvas2d/is there any issues implementing it?

**Comment by jagenjo** [comment]
Thanks!

it would be a huge work to implement the shadowblur.

The only way I see would be to have a secondary buffer, rendering on it the shapes, then having a thirth buffer to store the blurred version (this could require a fourth buffer), then drawing into the original buffer first the shadow then the secondary.

This process would be superslow, and prone to errors, and I dont have the time to endure in such endevour.

**Comment by AlexVestin** [comment]
@jagenjo Alright, thanks for the answer. Do you use any reference material for implementing this project?

**Comment by jagenjo** [comment]
no, sorry
