### ISSUE TITLE
globalCompositeOperation

### ISSUE THREAD

**Issue by WeslleyDeSouza** [jagenjo/Canvas2DtoWebGL#12]
is this now supported?

**Comment by jagenjo** [comment]
no, I haven't figure out the equivalent of the globalcompositeoperation modes with the blend modes of opengl

**Comment by dwdvIl** [comment]
What about creating custom shaders for it?

**Comment by jagenjo** [comment]
thats not how global composite operation works, as it doesnt involve shaders but blending operations

**Comment by dwdvIl** [comment]
> thats not how global composite operation works, as it doesnt involve shaders but blending operations

I'm not an expert at glsl programming, but i've always used shaders to do color math, i'm sure you can emulate almost all composite operations

**Comment by jagenjo** [comment]
shaders are not allowed to read the destination pixel. it can be overpass by rendering all to a texture, but that makes it way slower.
there is a extension proposed to solve this but it is not supported yet by browsers.
