### ISSUE TITLE
RangeError: Invalid typed array length: ...

### ISSUE THREAD

**Issue by Andrew-J-Larson** [jagenjo/Canvas2DtoWebGL#16]
When doing some complicated polygon operations, that I can normally do with regular canvas, your webGL library spits out that error instead... any specific reason?

Additionally I run into weird issues of it not filling in paths correctly for solid fills.

Here's the repl to see what I mean: https://repl.it/@TheAlienDrew/Snowflake-Polygon-Generator-WebGL#script.js

**Comment by jagenjo** [comment]
Hi:

Hard to debug as the repl doesnt show the error in the console.
But, why do you use Canvas2DtoWebGL? The performance will be much worse than  using the regular Canvas2D.
I see you are doing fractals, in that case you better use directly WebGL and fill a buffer with all the points.
