### ISSUE TITLE
not support Chinese！

### ISSUE THREAD

**Issue by nick-ye** [jagenjo/Canvas2DtoWebGL#19]
Wow, great job.
I simply tested some functions and found that the filltext() function does not support Chinese double bytes. I hope it can be repaired as soon as possible. I will use it in my game project. Please!
------
filltext( ‘你好中文’,50,50,50)

**Comment by jagenjo** [comment]
current fillText implementation uses a 256 characters atlas, a solution not suitable to languages with lots of characters (like chinese).

so chinese wont be supported.
