### ISSUE TITLE
Drawing between canvases

### ISSUE THREAD

**Issue by AlbinFarstun** [jagenjo/Canvas2DtoWebGL#20]
Thanks for your cool lib!
I tried it for fun as a drop-in replacement for canvas2D just to see if we could get a performance boost on our game.
Everything worked actually really fine out of the box except for when we draw stuff between canvases (since we're using only canvas I've made some functions to apply effects to images, like brighten, darken, dissolve etc, and here we use a buffer canvas where we manipulate the pixels directly). Of course, this could (and should, if we're using webgl) converted to just use fragment shaders instead, but I was wondering if you've tried to draw a canvas on another context with your solution?

What happens is that it basically seems to cache the original image and then all other calls to our per-pixel functions that uses the same canvas only get that same image back, however we manipulate the pixel data.

I could put together a super-basic minimal example of the problem (our game is not super-basic sadly) if this is something you would be interested in.

**Comment by jagenjo** [comment]
As you said, the regular process to apply any postprocessing FX to an image is to use a shader. You will draw the whole scene inside one texture, and then pass that texture through a shader when rendering to the canvas. You do not need a secondary canvas as WebGL can use textures as temporary buffer.

If you draw the output of one canvas into another canvas, chances are that the GPU needs to send the image to the CPU which will slowdown the rendering a lot. Some implementations of canvas may keep the image on the GPU as Canvas2D implementations already use the GPU for regular 2D render, but if you use getPixels then in will send the image to the CPU which will block the rendering and reduce the performance.

Canvas2DtoWebGL is built on top of litegl, if your goal is just to apply an FX to the rendered Canvas, then check the FBOs usage:
https://tamats.com/projects/litegl/examples/rendertexture_fbo.html
https://github.com/jagenjo/litegl.js/blob/master/examples/rendertexture_fbo.html

**Comment by AlbinFarstun** [comment]
Yes you're right!
Thank you.

Yes my goal is basically to be able to draw an image (or part of an image) with a shader applied to my final canvas, so I will go into the shader route :)

best regards.
