### ISSUE TITLE
The text rotation appears to have a bug, with extra points appearing in the transformation matrix for the rotation？

### ISSUE THREAD

**Issue by lithbitren** [jagenjo/Canvas2DtoWebGL#21]
![image](https://github.com/jagenjo/Canvas2DtoWebGL/assets/54011416/cf0f19d8-dc98-4c08-8625-653a6fb5bfa8)

**Comment by jagenjo** [comment]
yes, its a limitation, as I paint characters using gl_points, which are square so when rotated enter in the next character area.
